site_name: Mint Android SDK
site_description: Investwell Mint Android SDK Documentation
site_author: Laxmikant

repo_url: https://github.com/investwell-tools/mint-android-sdk
repo_name: mint-android-sdk

docs_dir: docs
site_dir: site

exclude_docs: |
  index.html


theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed

nav:
  - Home: index.md

  - SDK Guide:
      - Overview: sdk-overview.md
      - Installation: installation.md
      - Quick Start: quickstart.md

  - Versions:
      - 2.1.4: versions/2.1.4.md
      - 2.1.7: versions/2.1.7.md
